# audioset_suggestions.py
# ──────────────────────────────────────────────────────────────
#  AUDIOSET-BASED SUGGESTION LIBRARY
#  Based on PANNs AudioSet ontology (527 classes)
#  Edit this file to add/remove suggestion groups
# ──────────────────────────────────────────────────────────────

AUDIOSET_SUGGESTION_DICT = {
    # ── Gunshots & Weapons ────────────────────────────────────
    "gun":        ["gunshot", "gunfire", "gun shot", "firearms", "pistol shot",
                   "rifle shot", "machine gun", "cap gun", "bb gun"],
    "gunshot":    ["gunshot", "gunfire", "single gunshot", "multiple gunshots",
                   "pistol shot", "rifle shot", "shotgun blast"],
    "firearm":    ["firearm", "gun", "pistol", "rifle", "shotgun", "revolver",
                   "submachine gun", "machine gun", "artillery fire"],
    "rifle":      ["rifle", "rifle shot", "sniper shot", "assault rifle", "carbine"],
    "pistol":     ["pistol", "handgun", "revolver", "pistol shot", "semi-automatic"],
    "explosion":  ["explosion", "blast", "detonation", "bomb blast", "dynamite",
                   "explosive", "artillery shell", "grenade explosion", "fireball"],
    "bomb":       ["bomb", "bomb blast", "explosion", "detonation", "ied",
                   "landmine", "grenade", "mortar"],
    "artillery":  ["artillery", "cannon fire", "artillery fire", "mortar fire",
                   "howitzer", "tank fire", "shell explosion"],

    # ── Human Sounds ─────────────────────────────────────────
    "human":      ["human voice", "speech", "conversation", "talking", "whispering",
                   "shouting", "screaming", "singing", "humming", "laughing",
                   "crying", "coughing", "sneezing", "breathing", "yelling",
                   "chanting", "crowd noise", "babbling"],
    "speech":     ["speech", "human speech", "conversation", "talking", "dialogue",
                   "narration", "announcement", "monologue", "whispering"],
    "scream":     ["scream", "screaming", "shriek", "shrieking", "yell", "yelling",
                   "shout", "shouting", "cry", "wail", "wailing", "howl"],
    "shout":      ["shout", "shouting", "yell", "yelling", "scream", "screaming",
                   "cry out", "exclaim", "bellow"],
    "cry":        ["cry", "crying", "weeping", "sob", "sobbing", "wail", "wailing",
                   "whimper", "whimpering", "tears"],
    "laugh":      ["laugh", "laughing", "laughter", "giggle", "giggling", "chuckle",
                   "chuckling", "cackle", "snicker"],
    "whisper":    ["whisper", "whispering", "murmur", "murmuring", "hush",
                   "soft speech", "quiet talking"],
    "singing":    ["singing", "song", "vocal", "chant", "chanting", "choir",
                   "humming", "melody", "opera"],
    "cough":      ["cough", "coughing", "throat clearing", "hack", "wheeze"],
    "breathing":  ["breathing", "breath", "inhale", "exhale", "panting",
                   "gasping", "snoring", "hyperventilating"],
    "crowd":      ["crowd", "crowd noise", "crowd cheering", "audience",
                   "chanting crowd", "riot", "mob", "mass gathering"],

    # ── Animals ───────────────────────────────────────────────
    "dog":        ["dog barking", "bark", "barking", "dog", "puppy", "hound",
                   "growl", "growling", "howl", "howling", "whimper", "yelp"],
    "bark":       ["bark", "barking", "dog bark", "growl", "snarl", "yelp"],
    "cat":        ["cat", "meow", "meowing", "purr", "purring", "hiss",
                   "hissing", "cat screech"],
    "bird":       ["bird", "birdsong", "bird call", "tweet", "chirp", "chirping",
                   "singing bird", "crow", "cawing", "rooster", "cock crow",
                   "owl", "hooting", "parrot", "duck", "quacking"],
    "animal":     ["animal", "animal sound", "animal distress", "wildlife",
                   "beast", "creature sound"],
    "lion":       ["lion", "lion roar", "roar", "roaring", "big cat", "tiger roar"],
    "elephant":   ["elephant", "elephant call", "trumpet", "trumpeting"],
    "wolf":       ["wolf", "wolf howl", "howl", "howling", "coyote", "pack"],
    "insect":     ["insect", "cricket", "buzzing", "bee", "fly", "mosquito",
                   "cicada", "grasshopper"],
    "frog":       ["frog", "frog call", "croaking", "toad", "amphibian"],
    "horse":      ["horse", "neigh", "neighing", "gallop", "galloping", "hooves"],

    # ── Vehicles ──────────────────────────────────────────────
    "engine":     ["engine", "motor", "engine sound", "engine rev", "engine idle",
                   "engine noise", "engine start", "engine stop"],
    "car":        ["car", "automobile", "vehicle", "car engine", "car horn",
                   "car alarm", "car crash", "car door", "car skid"],
    "truck":      ["truck", "lorry", "heavy vehicle", "truck engine",
                   "truck horn", "semi truck", "diesel truck"],
    "motorcycle": ["motorcycle", "motorbike", "bike engine", "motorcycle rev",
                   "dirt bike", "chopper", "moped", "scooter"],
    "helicopter": ["helicopter", "chopper", "rotor", "helicopter blade",
                   "rotor wash", "helicopter engine"],
    "aircraft":   ["aircraft", "airplane", "plane", "jet", "jet engine",
                   "turbine", "propeller", "takeoff", "landing", "sonic boom"],
    "train":      ["train", "railway", "railroad", "train horn", "train whistle",
                   "locomotive", "rail", "subway", "metro", "tram"],
    "boat":       ["boat", "ship", "vessel", "boat engine", "marine engine",
                   "motorboat", "speedboat", "foghorn", "ship horn"],
    "vehicle":    ["vehicle", "car", "truck", "motorcycle", "engine",
                   "traffic", "road noise"],
    "ambulance":  ["ambulance", "ambulance siren", "emergency vehicle",
                   "paramedic", "ems"],
    "police":     ["police car", "police siren", "cop car", "law enforcement",
                   "patrol car"],
    "firetruck":  ["fire truck", "fire engine", "fire siren", "firefighter vehicle"],
    "tractor":    ["tractor", "farm vehicle", "agricultural machine", "bulldozer",
                   "excavator", "construction vehicle", "forklift"],

    # ── Industrial & Tools ────────────────────────────────────
    "drill":      ["drill", "drilling", "power drill", "electric drill",
                   "hand drill", "jackhammer", "pneumatic drill"],
    "saw":        ["saw", "sawing", "chainsaw", "circular saw", "band saw",
                   "hacksaw", "jigsaw", "table saw", "wood cutting"],
    "chainsaw":   ["chainsaw", "chain saw", "wood cutting", "tree cutting",
                   "logging", "chainsaw engine"],
    "grinder":    ["grinder", "grinding", "angle grinder", "metal grinding",
                   "bench grinder", "belt sander", "sanding"],
    "hammer":     ["hammer", "hammering", "nail gun", "nail hammering",
                   "sledgehammer", "jackhammer", "pile driver"],
    "welding":    ["welding", "arc welding", "torch", "welding torch",
                   "metal welding", "sparks"],
    "machine":    ["machine", "machinery", "industrial machine", "factory machine",
                   "conveyor belt", "press machine", "lathe", "milling machine"],
    "factory":    ["factory", "factory noise", "industrial", "manufacturing",
                   "plant noise", "assembly line", "production"],
    "compressor": ["compressor", "air compressor", "pneumatic", "pressurized air",
                   "pump", "hydraulic"],
    "generator":  ["generator", "power generator", "diesel generator",
                   "electric generator", "turbine generator"],
    "tool":       ["tool", "power tool", "hand tool", "electric tool",
                   "construction tool", "workshop"],

    # ── Alarms & Emergency ────────────────────────────────────
    "alarm":      ["alarm", "alarm sound", "siren", "alert", "warning alarm",
                   "smoke alarm", "fire alarm", "burglar alarm", "car alarm",
                   "klaxon", "buzzer", "beeping alarm"],
    "siren":      ["siren", "emergency siren", "police siren", "ambulance siren",
                   "fire siren", "air raid siren", "civil defense siren"],
    "smoke":      ["smoke alarm", "smoke detector", "fire alarm", "fire detector",
                   "carbon monoxide alarm"],
    "emergency":  ["emergency", "emergency alert", "sos", "distress signal",
                   "emergency broadcast", "mayday"],
    "horn":       ["horn", "car horn", "truck horn", "train horn", "foghorn",
                   "ship horn", "air horn", "klaxon"],
    "beep":       ["beep", "beeping", "alert tone", "notification", "buzzer",
                   "warning tone", "electronic beep"],

    # ── Nature & Weather ──────────────────────────────────────
    "thunder":    ["thunder", "thunderstorm", "thunderclap", "lightning",
                   "storm", "heavy storm", "thunder rumble"],
    "rain":       ["rain", "rainfall", "heavy rain", "light rain", "drizzle",
                   "downpour", "rainstorm", "raindrops"],
    "wind":       ["wind", "strong wind", "gust", "windstorm", "breeze",
                   "gale", "hurricane wind", "tornado wind"],
    "storm":      ["storm", "thunderstorm", "rainstorm", "windstorm", "blizzard",
                   "cyclone", "typhoon", "hurricane", "tornado"],
    "earthquake": ["earthquake", "tremor", "seismic", "ground rumble",
                   "aftershock", "landslide", "avalanche"],
    "flood":      ["flood", "flooding", "flash flood", "water rushing",
                   "river overflow", "surge"],
    "fire":       ["fire", "fire crackling", "burning", "flames", "wildfire",
                   "campfire", "bonfire", "fire roar"],
    "water":      ["water", "waterfall", "river", "stream", "ocean waves",
                   "waves", "surf", "splash", "flowing water", "brook"],
    "ocean":      ["ocean", "sea", "waves", "surf", "ocean waves",
                   "beach", "tide", "coastal"],

    # ── Music & Instruments ───────────────────────────────────
    "music":      ["music", "musical instrument", "song", "melody", "tune",
                   "rhythm", "beat", "harmony"],
    "drum":       ["drum", "drumming", "drum beat", "percussion", "snare",
                   "bass drum", "kick drum", "djembe"],
    "guitar":     ["guitar", "electric guitar", "acoustic guitar", "strumming",
                   "guitar riff", "bass guitar"],
    "piano":      ["piano", "keyboard", "keys", "piano music", "classical piano"],

    # ── Glass & Impact ────────────────────────────────────────
    "glass":      ["glass", "glass breaking", "glass shatter", "breaking glass",
                   "window breaking", "glass crash", "shards"],
    "crash":      ["crash", "collision", "impact", "smash", "thud",
                   "car crash", "vehicle collision", "crash sound"],
    "impact":     ["impact", "thud", "bang", "collision", "slam", "knock",
                   "hit", "strike", "punch"],
    "breaking":   ["breaking", "shatter", "crack", "snap", "split",
                   "fracture", "break"],

    # ── Domestic & Indoor ─────────────────────────────────────
    "door":       ["door", "door slam", "door knock", "door creak",
                   "door bell", "door open", "door close"],
    "footstep":   ["footstep", "walking", "running footsteps", "stomping",
                   "marching", "shuffling"],
    "typing":     ["typing", "keyboard", "keyboard typing", "computer keyboard",
                   "typewriter"],
    "phone":      ["phone", "telephone", "phone ring", "ringtone", "dial tone",
                   "mobile phone", "cell phone"],

    # ── Specific PANNs AudioSet Classes ───────────────────────
    "white noise":    ["white noise", "static", "noise", "hiss", "background noise"],
    "pink noise":     ["pink noise", "colored noise", "background hum"],
    "inside":         ["inside", "indoor", "interior", "room tone", "indoor ambience"],
    "outside":        ["outside", "outdoor", "exterior", "ambient", "open air"],
    "boat water":     ["boat water vehicle", "water vehicle", "motorboat", "speedboat"],
    "mechanical fan": ["mechanical fan", "fan noise", "ventilation", "hvac", "air conditioner"],
    "plop":           ["plop", "drip", "drop", "water drop", "liquid drop"],
    "click":          ["click", "clicking", "snap", "tick", "switch"],
    "scratch":        ["scratch", "scratching", "scrape", "scraping"],
    "thump":          ["thump", "thud", "bump", "low impact", "bass thump"],
}